apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: mosquitto
  name: mosquitto
spec:
  containers:
  - image: eclipse-mosquitto
    name: mosquitto
    ports:
    - containerPort: 1883
    - containerPort: 9001
    resources: {}
    volumeMounts:
    - mountPath: /mosquitto/mosquitto.conf
      name: mqtt-conf
  hostname: mosquitto
  restartPolicy: OnFailure
  volumes:
  - name: mqtt-conf
    persistentVolumeClaim:
      claimName: mqtt-conf
status: {}
