apiVersion: v1
kind: Pod
metadata:
  labels:
    io.kompose.service: weathersubscriber
  name: weathersubscriber
spec:
  containers:
  - args:
    - mosquitto_sub
    - -h
    - mosquitto
    - -t
    - weatherStation
    image: eclipse-mosquitto
    name: weathersubscriber
    resources: {}
  restartPolicy: OnFailure
status: {}
